### ISSUE TITLE
Metrics work TODO list

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#613]
- [ ] commits per week per repo
- [ ] star/fork counts for external folks only
- [ ] split engaged into 'conversing' and 'submitting' [distinction is Opening a Issue is more engaged than just conversing]
- [ ] running count of external submissions [PR's as well as opening an Issue]
- [ ] improve the reporting; single report?; publish to Serkay's web-page?

**Comment by mukul-seagate11** [comment]
@johnbent, can this issue be closed if done?

**Comment by mukul-seagate11** [comment]
@johnbent, can this issue be closed if no work is required?

**Comment by cortx-admin** [comment]
> Priyank  Dalal commented in Jira Server:

Verified
